# Generated by Django 4.2.2 on 2023-06-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_de_tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
